### ISSUE TITLE
php.ini - No such file or directory

### ISSUE THREAD

**Issue by njbair** [jippi/puppet-php#121]
I think this module is trying to write to the PHP.ini file before PHP is installed.

I'm getting these errors in Vagrant:

    ==> default: Notice: /Stage[main]/Php::Extension::Xdebug/Php::Extension[xdebug]/Package[php5-xdebug]/ensure: ensure changed 'purged' to 'present'
    ==> default: Notice: /Stage[main]/Phpmyadmin/Phpmyadmin::Debconf[reconfigure-webserver]/Exec[reconfigure-webserver]/returns: executed successfully
    ==> default: Notice: /Stage[main]/Php::Extension::Curl/Php::Extension[curl]/Package[php5-curl]/ensure: ensure changed 'purged' to 'present'
    ==> default: Notice: /Stage[main]/Php::Extension::Mysql/Php::Extension[mysql]/Package[php5-mysql]/ensure: ensure changed 'purged' to 'present'
    ==> default: Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
    ==> default: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/content: content changed '{md5}77f15d6c87f9c136c4efcda072017f71' to '{md5}790c6c49aed83ee9b81fa3c7360898c8'
    ==> default: Notice: /Stage[main]/Php::Augeas/File[/usr/share/augeas/lenses/contrib]/ensure: created
    ==> default: Notice: /Stage[main]/Php::Augeas/File[/usr/share/augeas/lenses/contrib/php.aug]/ensure: defined content as '{md5}3ee52fcce112525fd7b5297d361ab7ad'
    ==> default: Notice: /Stage[main]/Php::Extension::Xdebug/Php::Config[php-extension-xdebug]/Php::Config::Augeas[php-extension-xdebug]/Augeas[php-php-extension-xdebug-config]/returns: executed successfully
    ==> default: Error: Could not set 'present' on ensure: No such file or directory - /etc/php5/fpm/php.ini at 28:/tmp/vagrant-puppet/modules-ee68d6dc396f188d41daf4b584832de3/php/manifests/config/dwim.pp
    ==> default: Error: Could not set 'present' on ensure: No such file or directory - /etc/php5/fpm/php.ini at 28:/tmp/vagrant-puppet/modules-ee68d6dc396f188d41daf4b584832de3/php/manifests/config/dwim.pp
    ==> default: Wrapped exception:
    ==> default: No such file or directory - /etc/php5/fpm/php.ini
    ==> default: Error: /Stage[main]/Main/Php::Fpm::Config[post_max_size=64M]/Php::Config[post_max_size=64M]/Php::Config::Dwim[post_max_size=64M]/Ini_setting[post_max_size=64M in /etc/php5/fpm/php.ini]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/php5/fpm/php.ini at 28:/tmp/vagrant-puppet/modules-ee68d6dc396f188d41daf4b584832de3/php/manifests/config/dwim.pp
    ==> default: Notice: /Stage[main]/Php::Fpm::Package/Package[php5-fpm]/ensure: ensure changed 'purged' to 'present'

This is my PHP configuration:

    class { [ 'php::fpm', 'php::cli' ]: }
    class {
      [
        'php::extension::apcu',
        'php::extension::curl',
        'php::extension::mcrypt',
        'php::extension::mysql',
        'php::extension::xdebug',
      ]:
    }
    php::fpm::config { ['upload_max_filesize=64M', 'post_max_size=64M']: }
    php::fpm::config { 'listen=127.0.0.1:9000':
      file    => '/etc/php5/fpm/pool.d/www.conf',
      section => 'www',
    }

**Comment by igalic** [comment]
the problem here is that puppet will randomly order the execution.

but `php::fpm` needs to be ***evaluated*** before `php::fpm::config` can be used.

i think this is such a common bug, that we should fix it.

**Comment by njbair** [comment]
Is there currently a way to put config items inside the php::fpm call itself? Something like:

    class {  'php::fpm':
        config => { 'upload_max_filesize=64M' }
    }

That way you can control execution order within your module.

**Comment by igalic** [comment]
not yet.

**Comment by njbair** [comment]
After reading your reply about how Puppet orders things randomly, I read through some Puppet documentation and realized I can just add `require => Package['php5-fpm'] to the `php::fpm::config` function and everything works.

I think part of the reason this is such a common problem is that because PHP is so popular a lot of people trying to set this up are first-time Puppet users. They just don't know how it works or that they can use the `require` metaparameter in your functions.

Rather than code around the issue, I think a little documentation would go a long way. On the Docs > Configuration page, let users know about the `require` metaparameter:

> The default value for `$file` in this function is the actual PHP FPM configuration file, so be sure to require the PHP FPM package when calling this function. For example:

>    php::fpm::config { 'upload_max_filesize=20M':
>      require => Package['php5-fpm'],
>    }

**Comment by jippi** [comment]
Seem legit

**Comment by igalic** [comment]
@njbair i think a better solution is to place that code into `class php::fpm`…

**Comment by schkovich** [comment]
@igalic isn't this fixed with ea1ead55f02c927437abc7b8f4c84708866a7261?

**Comment by igalic** [comment]
most probably, and seeing as we haven't had any complaints recently, i'm closing it.
