### ISSUE TITLE
Must pass package_provider to Class[Php::Fpm::Package]

### ISSUE THREAD

**Issue by schkovich** [jippi/puppet-php#131]
@joshbetz pointed out in comment on the commit ea1ead55f02c927437abc7b8f4c84708866a7261 parameter _package_provider_ must be passed to the class _**php:fpm:package**_.
```bash
==> default: Must pass package_provider to Class[Php::Fpm::Package] at /tmp/vagrant-puppet-3/modules-0/php/manifests/fpm/package.pp:5
```
Most likely adding undef as default should do the trick. However I will have to test it before creating pull request.

**Comment by igalic** [comment]
yes, passing `undef` *will* do the trick.

**Comment by joshbetz** [comment]
I'm still seeing this issue on f3e9c84 :(

```
Must pass provider to Class[Php::Fpm::Service]
```

**Comment by schkovich** [comment]
Okay, but that is not the same error. I would prefer closing this issue and opening a new one.

**Comment by igalic** [comment]
ack
