### ISSUE TITLE
Must pass provider to Class[Php::Fpm::Service]

### ISSUE THREAD

**Issue by joshbetz** [jippi/puppet-php#134]
Similar to #131

**Comment by schkovich** [comment]
I will check for occurrence of any other similar cases.

**Comment by joshbetz** [comment]
@schkovich Any movement on this? I need to update this module to fix PHPUnit, but the latest version is broken. Would you recommend switching to a different php module?

**Comment by schkovich** [comment]
@joshbetz case you are steel facing the same problem reopen the issue please.

**Comment by joshbetz** [comment]
It seems to be fixed.
