### ISSUE TITLE
extensions installed but not enabled

### ISSUE THREAD

**Issue by roll4life** [jippi/puppet-php#142]
Environmental information: puppet 3.7, Ubuntu 14.04 (standard Ubuntu repositories)

Not sure if I am doing something wrong here, the issue I am having is with extensions.  The extensions will be installed and the initial files will be created in the following location:

```
/etc/php5/mods-available/
```

however no symlinks are created in the following directories like they would with an apt-get install php-x and php5enmod x

```
/etc/php5/fpm/conf.d
/etc/php5/apache2/conf.d
/etc/php5/cli/conf.d
```

when using

```
  class {
    ['::php::fpm', '::php::cli', ::php::dev]:
      ensure => 'installed';
    ['::php::extension::apc', '::php::extension::curl', '::php::extension::mcrypt', '::php::extension::pgsql']:
      ensure => 'installed'
  }
```

I initially thought that creating the resources would also handle the symlinks, but this does not appear to be the case

```
create_resources('php::apache::config', hiera_hash('php_apache_config', {}))
create_resources('php::cli::config', hiera_hash('php_cli_config', {}))
create_resources('php::fpm::config',  hiera_hash('php_fpm_config', {}))
```

so maybe for debian base systems there just needs to be a call that looks at all of the extensions that have been passed in and php5enmod can be run against those extension

Also when puppet is re-run any changes made to the extension files outside of puppet are not reset
e.g. 

```
/etc/php5/mods-available/apc.ini
```

default

```
extension=apcu.so
```

someone goes along and makes the following changes outside of puppet

```
extension=apcu.so                                                                                                        
[APCU]                                                                                                                   
apcu.enabled = 1                                                                                                         
apcu.shm_segments = 1                                                                                                    
apcu.shm_size = 64M
```

When puppet runs again these should be restored to default, but they are not

If you are doing more than the defaults, puppet will rewrite the file with no issues

```
php::config { 'enabled=1':
  file    => '/etc/php5/mods-available/apcu.ini',
  section => 'APCU',
}
php::config { 'shm_size=64M':
  file    => '/etc/php5/mods-available/apcu.ini'
  section => 'APCU',
}
```

**Comment by schkovich** [comment]
fixed in 59760d6
