### ISSUE TITLE
Errors for all module configs

### ISSUE THREAD

**Issue by ChrisWiegman** [jippi/puppet-php#151]
When attempting to use any module class I get the following errors:

Warning: Scope(Class[Php::Extension::[module name]::Params]): Could not look up qualified variable 'php::params::config_root_ini'; class php::params has not been evaluated

Classes are being called as follows:

class { 'php::extension::[module name]': }

**Comment by ChrisWiegman** [comment]
Looking further into this the issue appears to be with a change to the puppi module this last week. It looks like you changed params_lookup.rb to return undefined rather than an empty string (https://github.com/example42/puppi/commit/96d2e48969459968eac756a652a76d3980722b6d) which is causing the apt, apache and php modules to fail.

**Comment by schkovich** [comment]
@ChrisWiegman Are you sure that you opened issue at the right place? You are pointing to code change at **example42** [puppi](https://github.com/example42/puppi) repository while you opened issue at **jippi** [puppet-php](https://github.com/jippi/puppet-php) project.

**Comment by ChrisWiegman** [comment]
While the issue turned out to eventually be with Puppi I opened it here before tracking it down as it was affecting every Example42 module I tried.
