### ISSUE TITLE
How do I can install yaml php extension?

### ISSUE THREAD

**Issue by Poplava** [jippi/puppet-php#76]
... or how do I can install any other PECL extension which doesn't present in supported extension list?

Thanks!

**Comment by schkovich** [comment]
It sounds as if extensions where not enabled. Default way of enabling PHP extension on Debian is to execute ```php5enmod x````which will create symbolic links in each SAPI configuration directory. When installing extension using package manager this command will be executed as a part of installation script. On the other hand when installing extension using PECL provider corresponding ini file will be created in /etc/php5/mods-available but command _php5enmod_ will not be executed. See #142.

**Comment by schkovich** [comment]
fixed in 59760d6
